### ISSUE TITLE
will you release the train code?

### ISSUE THREAD

**Issue by visonpon** [B10532021/Part-Aware_Measurement_for_3D_Pose_Estimation_and_Tracking#1]
Hi, thanks for sharing this wonderful work, will you release the training part code thanks?

**Comment by B10532021** [comment]
Hi, 
Since only 2D pose estimation part involved deep learning model, other parts are mostly traditional method, like epipolar geometry, so there's no training part. However, 2D pose estimation isn't our main contribution. I have mentioned the deep learning model we referenced from in README.md, you can linked to their page for more information. Also, we use YOLOv3 for human detection and HRNet for pose estimation, I believed there are lots of resources about how to train these model out there.

Thanks for asking!
